 var arrinfo = ["Имя браузера:<br>navigator.appName", 
	       "Ширина экрана:  ", 
		   "Высота экрана: ",
		   "высота рабочей области экрана в пикселях (исключая высоту панели задач):<br>screen.availHeight", 
		   "Ширина активного экрана:<br>screen.availWidth", 
		   "Битовая глубина цветовой палитры:<br>screen.colorDepth",
		   "Текущая ориентация экрана:<br>screen.orientation.type", 
		   "Кодовое имя браузера:<br>navigator.appCodeName", 
           "Включена ли поддержка cookie?<br>navigator.cookieEnabled", 
		   "Включена ли поддержка Java в браузере?<br>navigator.javaEnabled", 
		   " online?<br>navigator.onLine",
		   "Полная информация о браузере:<br>navigator.userAgent",
		   "Перейти на указанную n-ую URL в списке посещенных страниц:",
		   "Перейти на следующую страницу, как если бы посетитель нажал на кнопку браузера Вперед:",
		   "Перейти на предыдущую страницу, как если бы посетитель нажал на кнопку браузера Назад:",
		   "Количество URL которые хранятся в History:<br>history.length",
		   "Часть URL, которая идет после символа решетки '#', включая символ '#':<br>location.hash",
		   "Xост и порт:<br>location.host","Весь URL:<br>location.href",
		   "Hомер порта:<br>location.port","Протокол:<br>location.protocol",
		   "Часть адреса после символа ?, включая символ ?:<br>location.search",
		   "Перезагрузить документ по текущему UR:",
		   "Загрузить документ по данному url:",
		   "Определяет x-координату указателя относительно экрана в момент возникновения события:<br>screenX/screenLeft",
		   "Определяет y-координату указателя относительно экрана в момент возникновения события:<br>screenY/screenTop",
		   "прокрутка документа по горизонтали относительного левого верхнего угла окна:<br>scrollX",
		   " прокрутка документа по вертикали относительного левого верхнего угла окна:<br>scrollY",
		   "Метод прокручивает страницу относительно текущих координат:",
		   "Метод прокручивает страницу к указанным координатам относительно документа:",
		   "Метод закрывает указанное окно:",
		   "Ширина рабочей области окна:<br>innerWidth",
		   "Высота рабочей области окна:<br>innerHeight",
		   "открывает в новом окне:",
		   "печатает текущую страницу:"]; 
var arr2 = [ navigator.appName, screen.width, screen.height, screen.availHeight, screen.availWidth, screen.colorDepth, screen.orientation.type, navigator.appCodeName, navigator.cookieEnabled, navigator.javaEnabled,navigator.onLine,navigator.userAgent,
"history.go()","history.forward()","history.back()",history.length,location.hash,location.host,location.href,location.port,location.protocol,location.search,"location.reload()","location.assign()",screenX, screenY,scrollX,scrollY,"scrollBy(x,y)","scrollTo(pageX,pageY)",
"close()",innerWidth,innerHeight,"open()","print()"]; 
document.write("<table border='1'><tr><th>Property</th><th>Result</th></tr>"); 
for (var i = 0; i < arrinfo.length; i++){ 
	document.write("<tr><th width='55%'><p>" + arrinfo[i] + "<p></th><th width='40%'><p>" + arr2[i] + "</p></th></tr>"); 
}